# Generated by Django 4.1 on 2022-08-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jopType',
            new_name='jop_type',
        ),
    ]
