# Generated by Django 4.1 on 2022-08-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_joptype_job_jop_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jop_type',
            new_name='job_type',
        ),
    ]
